//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MUSTERITABLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSTERITABLO()
        {
            this.SATISTABLO = new HashSet<SATISTABLO>();
        }
    
        public int musteriID { get; set; }

        [Required(ErrorMessage = "*Bu alaný boþ býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "*Bu alana en fazla 50 karakter girebilirsiniz.")]
        public string musteriAd { get; set; }

        [Required(ErrorMessage = "*Bu alaný boþ býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "*Bu alana en fazla 50 karakter girebilirsiniz.")]
        public string musteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATISTABLO> SATISTABLO { get; set; }
    }
}
