//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class URUNTABLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNTABLO()
        {
            this.SATISTABLO = new HashSet<SATISTABLO>();
        }
    
        public int urunID { get; set; }
        public string uurnAd { get; set; }
        public string urunMarka { get; set; }
        public Nullable<short> urunKategori { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<byte> urunStok { get; set; }
    
        public virtual KATEGORITABLO KATEGORITABLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATISTABLO> SATISTABLO { get; set; }
    }
}
